# Generated by Django 4.0.6 on 2022-08-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
